### ISSUE TITLE
Whats is this? ImportError: cannot import name 'MAGIC_FIRST' from 'wikitextprocessor'

### ISSUE THREAD

**Issue by crashangelbr** [tatuylonen/wikitextprocessor#3] opened 2021-09-14 16:50 UTC
What is this error? 

ImportError: cannot import name 'MAGIC_FIRST' from 'wikitextprocessor' (/home/romeu/.local/lib/python3.9/site-packages/wikitextprocessor/__init__.py)

**Comment by tatuylonen** [comment] 2021-12-07 13:52
Sorry I had not been monitoring issues in this project (I have mostly been working on the wiktextract side in recent months) and hadn't noticed this issue.  It was probably caused by a version mismatch between wikitextprocessor and wiktextract (probably wikitextprocessor needing to be updated to the most recent version from the repository). Closing.

**Closed by tatuylonen** 2021-12-07 13:52 UTC
